import { motion } from 'framer-motion';
import { ArrowDownRight, BarChart3, Layers3 } from 'lucide-react';
import { ContributionGraph } from '../components/ContributionGraph';
import { Navbar } from '../components/Navbar';
import { ProfileCard } from '../components/ProfileCard';
import { RepoCard } from '../components/RepoCard';
import { SearchBar } from '../components/SearchBar';
import { StatsCard } from '../components/StatsCard';

export function Home() {
  return <main className="page-shell"><div className="ambient ambient-blue" /><div className="ambient ambient-purple" /><div className="ambient ambient-green" /><Navbar /><section className="hero"><motion.div className="hero-copy" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7, ease: 'easeOut' }}><div className="glass-badge"><span className="badge-pulse" />Explore GitHub developers <ArrowDownRight size={14} /></div><h1>Understand the <span>&lt;code&gt;</span><br />behind developers.</h1><p>Explore the people, projects, and patterns shaping the open-source world.</p><SearchBar /><div className="trust-note"><span className="trust-dot" />Built for curious minds <span className="note-divider" /> Private by design</div></motion.div></section><motion.section className="dashboard-preview" initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, delay: 0.35, ease: 'easeOut' }}><div className="preview-toolbar"><span className="preview-label"><span /> LIVE PREVIEW</span><span className="preview-context">A glimpse into your next profile exploration <ArrowDownRight size={13} /></span></div><div className="dashboard-grid"><div className="dashboard-main"><ProfileCard /><div className="stats-grid"><StatsCard label="Contributions" value="1,248" detail="+18.4% this year" icon="↗" /><StatsCard label="Repositories" value="86" detail="12 recently active" icon="⌘" /><StatsCard label="Languages" value="09" detail="Across all projects" icon="◌" /></div><ContributionGraph /></div><aside className="repositories preview-surface"><div className="section-heading"><div><span className="eyebrow">SELECTED WORK</span><h3>Repositories</h3></div><Layers3 size={16} /></div><RepoCard name="signal-flow" description="A toolkit for expressive data visualizations." language="TypeScript" color="#5e9cff" stars="248" /><RepoCard name="orbit-ui" description="Thoughtful primitives for modern interfaces." language="React" color="#61dafb" stars="184" /><div className="language-panel"><div className="language-title"><span>Language mix</span><BarChart3 size={15} /></div><div className="language-bar"><i /><i /><i /><i /></div><div className="language-legend"><span><b className="blue" />TypeScript <em>42%</em></span><span><b className="pink" />CSS <em>28%</em></span><span><b className="yellow" />JavaScript <em>18%</em></span></div></div></aside></div></motion.section><footer><span>GitExplore <b>·</b> Developer intelligence, made clear.</span></footer></main>;
}
